name: wsk
version: 0.5.1
authors:
- Google team
- Hiroshi Yamamoto <higon@freepress.jp>
description: A light-weight asset/template pack for Google's Web Starter Kit. \r\nThis includes pre-compiled resources, auxiliary methods, and a project template.
homepage: https://github.com/hyamamoto/web-starter-kit.dart
environment:
  sdk: '>=1.2.0'
documentation: https://github.com/hyamamoto/web-starter-kit.dart
dependencies:
  barback: any
  browser: any
  route_hierarchical: any
  html5lib: '>=0.8.9 <0.13.0'
dev_dependencies:
  unittest: '>=0.6.0 <0.12.0'
